# Matrix Multiplication with NumPy and Scratch Implementation

## 1. Goal
This assignment requires learners to:
- Understand basic matrix operations using NumPy
- Implement matrix multiplication from scratch

## 2. Understanding Matrix Multiplication


In [ ]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3],
                      [4, -5, 6],
                      [7, 8, -9]]) # defined in the material

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]]) # ditto

print("Matrix A:\n", a_ndarray)
print("Matrix B:\n", b_ndarray)

Matrix A:
 [[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Matrix B:
 [[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


## 3. Manual Calculation Concept
Done manually


## 4. NumPy Matrix Multiplication
NumPy provides several ways to multiply matrices: `np.matmul`, `np.dot`, and the `@` operator.

In [ ]:
# Using different methods; all give the same result
result_matmul = np.matmul(a_ndarray, b_ndarray)
result_dot = np.dot(a_ndarray, b_ndarray)
result_at = a_ndarray @ b_ndarray

print("Result via matmul:\n", result_matmul)
print("Result via dot method:\n", result_dot)
print("Result via @ operator:\n", result_at)
print("Check equality:", np.array_equal(result_matmul, result_dot), np.array_equal(result_matmul, result_at))

Result via matmul:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Result via dot method:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Result via @ operator:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Check equality: True True


## 5. Scratch Implementation
This assignment requires implementing matrix multiplication by hand.  


In [ ]:
# Write the function as shown in material
def matmul_scratch(a, b):
    result = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]
    return result

scratch_result = matmul_scratch(a_ndarray, b_ndarray)
print("Scratch implementation result:\n", scratch_result)
print("Matches NumPy?", np.allclose(scratch_result, result_matmul))

Scratch implementation result:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
Matches NumPy? True


## 6. When Multiplication Is Undefined
The product is undefined unless the number of columns of the first matrix equals the number of rows of the second.

Example matrices D (2×3) and E (2×3) cannot be multiplied directly.

In [ ]:
d_ndarray = np.array([[-1, 2, 3],
                      [4, -5, 6]])

e_ndarray = np.array([[-9, 8, 7],
                      [6, -5, 4]])

print("Shape D:", d_ndarray.shape)
print("Shape E:", e_ndarray.shape)

def is_multiplicable(a, b):
    if a.shape[1] != b.shape[0]:
        print("Matrix product undefined: columns of A != rows of B")
        return False
    return True

if is_multiplicable(d_ndarray, e_ndarray):
    print(np.matmul(d_ndarray, e_ndarray))

Shape D: (2, 3)
Shape E: (2, 3)
Matrix product undefined: columns of A != rows of B


## 7. Using Transposition
Sometimes multiplication becomes possible if one matrix is transposed.  
This assignment requires checking multiplication with `E.T`.

In [ ]:
e_transposed = e_ndarray.T
if is_multiplicable(d_ndarray, e_transposed):
    result_transposed = np.matmul(d_ndarray, e_transposed)
    print("Result of D × E.T:\n", result_transposed)

Result of D × E.T:
 [[ 46  -4]
 [-34  73]]


## 8. Conclusion
The findings here demonstrate that:
- Matrix multiplication combines rows of the first with columns of the second
- NumPy provides efficient built-in methods
- Scratch implementations deepen understanding
- Multiplication rules depend on shapes; transposition can enable compatibility